version: "3"
services:

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
    ports:
      - 5432:5432  
    volumes:
      - ./data:/var/lib/postgres/data

  
